name: Build No Name Game APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          export PATH=$PATH:$(go env GOPATH)/bin
          gomobile init

      - name: Compile Go to Android library (.aar)
        run: |
          gomobile bind -target=android -o no-name-game.aar ./no-name-game.go

      - name: Clone Android wrapper app
        run: |
          git clone https://github.com/adiwajshing/GoAndroidWrapper.git wrapper
          mkdir -p wrapper/app/libs
          cp no-name-game.aar wrapper/app/libs/

      - name: Build APK
        run: |
          cd wrapper
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: no-name-game-apk
          path: wrapper/app/build/outputs/apk/debug/app-debug.apk
